name: Reusable Container Check

on:
  workflow_call:
    inputs:
      path_file:
        required: true
        type: string
      test_number:
        required: true
        type: string
jobs:
  container-check:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4.2.1
          with:  
            fetch-depth: 0
        - uses: stack-spot/stk-cli-action@v1.2
          with:
            client_id: ${{ secrets.STK_CLIENT_ID }}
            client_key: ${{ secrets.STK_CLIENT_KEY }}
            realm: stackspot    
        - run: stk run action $GITHUB_WORKSPACE/container-check --stk_client_id '${{secrets.STK_CLIENT_ID}}' --stk_client_key '${{secrets.STK_CLIENT_KEY}}'
          env:
            FEATURES_LEVEL_LOG: debug
        - name: Push changes and Open Pull Request
          run: python pr_script.py
          shell: bash
          env:
            GITHUB_TOKEN: ${{ github.token }}
            GITHUB_WORKSPACE: ${{ github.workspace }}
            GITHUB_REPOSITORY: GuillaumeFalourd/stackspot-actions
            TEST_NUMBER: ${{ inputs.test_number }}
            PATH_FILE: ${{ inputs.path_file }}
        - run: |
                - name: Push changes and Open Pull Request
          id: commit_push
          run: |
            if [[ `git status --porcelain` ]]; then
              git config --global user.name "stackspot[bot]"
              git config --global user.email "stackspot[bot]@users.noreply.github.com"
              git checkout main
              git pull origin main --ours
              git add .
              git commit -m "Update ${{ inputs.path_file }} with data"
              git push origin main
            else
              echo "WARNING: No changes were detected."
            fi
