name: Reusable Container Check

on:
  workflow_call:
    inputs:
      path_file:
        required: true
        type: string
      test_number:
        required: true
        type: string
jobs:
  container-check:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4.2.1
          with:  
            fetch-depth: 0
        - uses: stack-spot/stk-cli-action@v1.2
          with:
            client_id: ${{ secrets.STK_CLIENT_ID }}
            client_key: ${{ secrets.STK_CLIENT_KEY }}
            realm: stackspot    
        - run: stk run action $GITHUB_WORKSPACE/container-check --stk_client_id '${{secrets.STK_CLIENT_ID}}' --stk_client_key '${{secrets.STK_CLIENT_KEY}}'
          env:
            FEATURES_LEVEL_LOG: debug
        - name: Open Pull Request
          run: python pr_script.py
          shell: bash
          env:
            GITHUB_TOKEN: ${{ github.token }}
            GITHUB_WORKSPACE: ${{ github.workspace }}
            GITHUB_REPOSITORY: GuillaumeFalourd/stackspot-actions
            TEST_NUMBER: ${{ inputs.test_number }}
            PATH_FILE: ${{ inputs.path_file }}
        - name: Push CSV file on main
          run: |
            git branch
            git status
            if [[ `git status --porcelain` ]]; then
              # Stash the changes
              git stash

              # Pull the latest changes from the remote branch, ignoring conflicts
              git fetch origin main
              git reset --hard origin/main

              # Apply the stashed changes
              git stash pop

              # Stage and commit the changes
              git add .
              git commit -m "Update ${{ inputs.path_file }} with new data."

              git status

              # Push the changes to the remote branch
              git push origin main --force
            else
              echo "WARNING: No changes were detected."
            fi
          shell: bash
