name: Vulnerability Check

on:
  # push:
  schedule:
    - cron: "0 1 * * MON-FRI" # Runs at 01:00 UTC
  workflow_dispatch:

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stack-spot/stk-cli-action@v1.2
        with:
          client_id: ${{ secrets.STK_CLIENT_ID }}
          client_key: ${{ secrets.STK_CLIENT_KEY }}
          realm: stackspot    
      - run: stk run action $GITHUB_WORKSPACE/vulnerability-check --stk_client_id '${{secrets.STK_CLIENT_ID}}' --stk_client_key '${{secrets.STK_CLIENT_KEY}}'
        env:
          FEATURES_LEVEL_LOG: debug
